// compute — Tensix Compute kernel
//
// Reads one tile from game_dfb (CB 0), copies it to out_dfb (CB 1).
// This is the Tensix compute thread, generated by TT-Lang from
// ttlang/zork_kernel_hw.py and beautified (renamed v1-v2, added comments).
//
// Stub behaviour (current):
//   Passes the game tile through to the output DFB unchanged using copy_tile.
//   Proves the CB pipeline is wired correctly end-to-end.
//
// Full implementation (future):
//   Replace copy_tile with Z-machine interpreter logic:
//     1. Accumulate all 85 game tiles from game_dfb into interpreter memory.
//     2. Execute ZMachineV3.interpret(100) — run 100 Z-machine instructions.
//     3. Flush text output into out_dfb tiles for dm_writer to send to DRAM.
//
// Key Tensix compute API calls:
//   cb_wait_front  — wait for dm_reader to push a tile into game_dfb
//   cb_reserve_back — reserve space in out_dfb for the output tile
//   copy_tile_init — configure the copy operation (source CB)
//   copy_tile      — copy tile from source CB slot to dst register (index 0)
//   pack_tile      — pack register to destination CB slot
//   cb_pop_front   — release the consumed source tile back to the pool
//   cb_push_back   — signal dm_writer that the output tile is ready

#include <cstdint>
#include "tools/profiler/kernel_profiler.hpp"
#include "internal/firmware_common.h"
#include "llk_defs.h"
#include "api/compute/binary_max_min.h"
#include "api/compute/common.h"
#include "api/compute/matmul.h"
#include "api/compute/bcast.h"
#include "api/compute/tilize.h"
#include "api/compute/untilize.h"
#include "api/compute/transpose_wh.h"
#include "api/compute/eltwise_binary.h"
#include "api/compute/eltwise_binary_sfpu.h"
#include "api/compute/add_int_sfpu.h"
#include "api/compute/sub_int_sfpu.h"
#include "api/compute/mul_int_sfpu.h"
#include "api/compute/compute_kernel_api.h"
#include "api/compute/copy_dest_values.h"
#include "api/compute/tile_move_copy.h"
#include "api/compute/eltwise_unary/activations.h"
#include "api/compute/eltwise_unary/eltwise_unary.h"
#include "api/compute/eltwise_unary/exp.h"
#include "api/compute/eltwise_unary/sfpu_split_includes.h"
#include "api/compute/eltwise_unary/recip.h"
#include "api/compute/eltwise_unary/fill.h"
#include "api/compute/eltwise_unary/negative.h"
#include "api/compute/eltwise_unary/sqrt.h"
#include "api/compute/eltwise_unary/rounding.h"
#include "api/compute/eltwise_unary/trigonometry.h"
#include "api/compute/eltwise_unary/gelu.h"
#include "api/compute/eltwise_unary/erf_erfc.h"
#include "api/compute/eltwise_unary/logical_not.h"
#include "api/compute/eltwise_unary/comp.h"
#include "api/compute/eltwise_unary/rsqrt.h"
#include "api/compute/eltwise_unary/typecast.h"
#include "api/compute/binary_bitwise_sfpu.h"
#include "api/compute/eltwise_unary/bitwise_not.h"
#include "api/compute/eltwise_unary/relu.h"
#include "api/compute/eltwise_unary/binop_with_scalar.h"
#include "api/compute/eltwise_unary/where.h"
#include "api/compute/eltwise_unary/clamp.h"
#include "api/compute/pack_untilize.h"
inline uint32_t float_to_bits(float f) { uint32_t r; __builtin_memcpy(&r, &f, sizeof(r)); return r; }
#ifndef INFINITY
#define INFINITY __builtin_inff()
#endif
#define REDUCE_OP PoolType::SUM
#define REDUCE_DIM ReduceDim::REDUCE_COL
#include "api/compute/reduce.h"

void kernel_main() {
    // Compile-time CB indices (set by host runner compile_time_args = [0, 1]).
    const int32_t cb_game_dfb  = get_compile_time_arg_val(0);  // input  — game data
    const int32_t cb_out_dfb   = get_compile_time_arg_val(1);  // output — result text

    // num_tiles = 1: process one 32×32 tile per loop iteration (stub: one iteration).
    const int32_t num_tiles    = 1;
    // dst_tile_idx = 0: single tile slot in the destination register file.
    const size_t  dst_tile_idx = 0;

    // --- Wait for dm_reader to push a game tile into CB 0 ---
    cb_wait_front(cb_game_dfb, num_tiles);

    // --- Reserve space in CB 1 for the output tile ---
    cb_reserve_back(cb_out_dfb, num_tiles);

    // --- Copy tile from game_dfb to out_dfb (STUB: passthrough) ---
    // Full impl: replace with Z-machine interpret() + text output packing.
    init_sfpu(cb_game_dfb, cb_out_dfb);   // initialise SFPU for the CB pair
    tile_regs_acquire();                   // acquire exclusive access to tile register file
    copy_tile_init(cb_game_dfb);           // configure copy source = game_dfb
    copy_tile(cb_game_dfb, dst_tile_idx, dst_tile_idx);  // copy tile[0] → dst reg[0]
    tile_regs_commit();                    // release tile regs to packer
    tile_regs_wait();                      // wait for packer to acquire tile regs
    pack_tile<true>(dst_tile_idx, cb_out_dfb, dst_tile_idx);  // pack reg[0] → out_dfb
    tile_regs_release();                   // release tile regs back to unpacker

    // --- Push output tile to out_dfb, release consumed input ---
    cb_push_back(cb_out_dfb, num_tiles);   // signal dm_writer that out_dfb[0] is ready
    cb_pop_front(cb_game_dfb, num_tiles);  // release game_dfb[0] back to dm_reader

    return;
}
