// dm_reader — Data Movement Reader kernel
//
// Loads the first tile of Z-machine game data from DRAM into L1 circular
// buffer CB 0 (game_dfb), then signals the compute thread that data is ready.
//
// This is the RISC-V DM0 thread, generated by TT-Lang from
// ttlang/zork_kernel_hw.py and beautified (renamed v1-v7, added comments).
//
// Tensor layout (game tensor is (2720, 32) bfloat16 TILE_LAYOUT in DRAM):
//   Each row holds TILE_SIZE=32 bytes of game data.
//   Tile (r_t, 0) = rows [r_t*32:(r_t+1)*32, 0:32] = bytes [r_t*1024:(r_t+1)*1024].
//   tile_index=0 = tile(0,0) = game bytes 0-1023 (Z-machine header at 0-63).
//
// Full implementation (future):
//   Loop over all 85 game tiles, issuing cb_reserve_back / noc_async_read_tile /
//   noc_async_read_barrier / cb_push_back for each one, coordinating with the
//   compute thread via the double-buffered CB producer/consumer protocol.

#include <cstdint>
#include "tools/profiler/kernel_profiler.hpp"
#include "internal/firmware_common.h"
#include "api/dataflow/dataflow_api.h"

void kernel_main() {
    // Compile-time args: CB indices for game_dfb (CB 0) and out_dfb (CB 1).
    // set by the host runner's compile_time_args list = [cb_game_dfb, cb_out_dfb].
    const int32_t cb_game_dfb  = get_compile_time_arg_val(0);  // game DFB (producer)
    // cb_out_dfb unused in reader; writer uses it.

    // page_size = 2048 bytes = one bfloat16 tile (32×32 × 2 bytes/element).
    const int32_t page_size    = 2048;
    // num_tiles = 1: read one tile per invocation (stub reads only tile 0).
    const int32_t num_tiles    = 1;
    // tile_index = 0: read the first tile (bytes 0-1023) from DRAM.
    const int32_t tile_index   = 0;

    // Runtime arg 0: buffer address of the game tensor in DRAM.
    // Passed by host via common_runtime_args = [game_tensor.buffer_address()].
    const size_t  rt_arg_game  = 0;

    // --- CB producer protocol: reserve → DMA → push ---

    // Reserve space in game_dfb for num_tiles tiles (blocks until compute has
    // consumed the previous block, maintaining double-buffer throughput).
    cb_reserve_back(cb_game_dfb, num_tiles);

    // Construct TensorAccessor for the game DRAM tensor.
    // This encodes stride, DRAM bank routing, and bfloat16 tile addressing.
    const int32_t game_buf_addr = get_common_arg_val<uint32_t>(rt_arg_game);
    auto game_accessor_args = TensorAccessorArgs<
        tensor_accessor::detail::get_tensor_accessor_args_cta_offset<0, 2>(), 0>();
    TensorAccessor game_accessor = TensorAccessor(game_accessor_args, game_buf_addr, page_size);

    // L1 write pointer: where in CB L1 memory the tile data will be deposited.
    const int32_t l1_write_ptr = get_write_ptr(cb_game_dfb);

    // Issue async NoC read: DRAM tile[tile_index] → L1 at l1_write_ptr.
    noc_async_read_tile(tile_index, game_accessor, l1_write_ptr);
    // Barrier: stall until DMA completes before signalling compute.
    noc_async_read_barrier();

    // Signal to compute that the tile is ready in CB game_dfb.
    cb_push_back(cb_game_dfb, num_tiles);

    return;
}
