// dm_writer — Data Movement Writer kernel
//
// Waits for the compute thread to push a tile into out_dfb (CB 1), then
// writes that tile from L1 back to DRAM in the output tensor.
// This is the RISC-V DM1 thread, generated by TT-Lang from
// ttlang/zork_kernel_hw.py and beautified (renamed v1-v7, added comments).
//
// Tensor layout (output tensor is (512, 32) bfloat16 TILE_LAYOUT in DRAM):
//   Each row holds 32 bytes. tile(r_t, 0) = bytes [r_t*1024:(r_t+1)*1024].
//   tile_index=0 → output bytes 0-1023 (first tile of output).
//
// After this kernel completes, output_tensor[0:32, 0:32] contains the
// first tile of game data (stub), which the host reads back to verify.
//
// Full implementation (future):
//   Drain multiple output tiles produced by the interpreter, writing each
//   one to successive tile slots in the output DRAM tensor.

#include <cstdint>
#include "tools/profiler/kernel_profiler.hpp"
#include "internal/firmware_common.h"
#include "api/dataflow/dataflow_api.h"

void kernel_main() {
    // Compile-time CB indices (set by host runner compile_time_args = [0, 1]).
    // Writer uses CB 1 (out_dfb) as its source.
    const int32_t cb_game_dfb  = get_compile_time_arg_val(0);  // game DFB (unused here)
    const int32_t cb_out_dfb   = get_compile_time_arg_val(1);  // output DFB (consumer)

    // page_size = 2048 bytes = one bfloat16 tile (32×32 × 2 bytes/element).
    const int32_t page_size    = 2048;
    // num_tiles = 1: write one tile per invocation (stub writes only tile 0).
    const int32_t num_tiles    = 1;
    // tile_index = 0: write the first tile slot in the output DRAM tensor.
    const int32_t tile_index   = 0;

    // Runtime arg 0 for writer thread: buffer address of the output tensor in DRAM.
    // Passed by host via common_runtime_args = [output_tensor.buffer_address()].
    const size_t  rt_arg_output = 0;

    // --- Wait for compute to push an output tile into out_dfb ---
    cb_wait_front(cb_out_dfb, num_tiles);

    // --- Write tile from L1 out_dfb to DRAM output tensor ---

    // Construct TensorAccessor for the output DRAM tensor.
    const int32_t out_buf_addr = get_common_arg_val<uint32_t>(rt_arg_output);
    auto out_accessor_args = TensorAccessorArgs<
        tensor_accessor::detail::get_tensor_accessor_args_cta_offset<1, 2>(), 0>();
    TensorAccessor out_accessor = TensorAccessor(out_accessor_args, out_buf_addr, page_size);

    // L1 read pointer: where in CB L1 memory the tile data sits.
    const int32_t l1_read_ptr = get_read_ptr(cb_out_dfb);

    // Issue async NoC write: L1 at l1_read_ptr → DRAM tile[tile_index].
    noc_async_write_tile(tile_index, out_accessor, l1_read_ptr);
    // Barrier: stall until DMA completes before releasing the CB slot.
    noc_async_write_barrier();

    // Release the output tile back to the CB pool (compute can reuse it).
    cb_pop_front(cb_out_dfb, num_tiles);

    return;
}
