/**
 * split_screen.h - Split-Screen TUI Interface for Zork
 *
 * OVERVIEW
 * ========
 * This module provides a modern split-screen terminal user interface (TUI)
 * for Zork that displays:
 * - Header bar with game title and LLM agent status
 * - Main game area (70% width) for Z-machine text output
 * - Right sidebar (30% width) for ASCII art, inventory, journey map
 * - Footer bar for command input
 *
 * ARCHITECTURE
 * ============
 * This is a thin display layer that wraps the existing "dumb" interface.
 * It doesn't modify game logic - just changes where text appears.
 *
 * Flow:
 *   Z-machine → os_display_string() → output_capture_add() → tui_display_text()
 *                                                                    ↓
 *                                                            [ncurses window]
 *
 * DESIGN PHILOSOPHY
 * =================
 * - Non-intrusive: Can be toggled on/off with ZORK_TUI_DISABLE env var
 * - Modular: Standalone, doesn't touch Z-machine internals
 * - Simple: ~300 lines vs 5000 lines of Frotz curses
 *
 * USAGE
 * =====
 * Initialize once at startup:
 *   tui_init();
 *
 * Display game text (called from os_display_string):
 *   tui_display_text("West of House\n");
 *
 * Update sidebar when location changes:
 *   tui_update_sidebar();
 *
 * Get user input:
 *   char *cmd = tui_read_input("> ");
 *
 * Cleanup on exit:
 *   tui_shutdown();
 *
 * ENVIRONMENT VARIABLES
 * =====================
 * ZORK_TUI_DISABLE=1  - Disable TUI, use plain text output
 *
 * TERMINAL REQUIREMENTS
 * =====================
 * - Minimum 80x24 characters (80 cols recommended for proper layout)
 * - Unicode/UTF-8 support for emojis (optional, gracefully degrades)
 * - Color support (optional, uses monochrome if unavailable)
 */

#ifndef TT_ZORK_TUI_SPLIT_SCREEN_H
#define TT_ZORK_TUI_SPLIT_SCREEN_H

/* TUI uses standard bool from C99
 * Note: When included from Frotz code, there may be bool type conflicts.
 * Frotz defines bool as int, but ncurses requires C99 bool (_Bool).
 * We use C99 bool here since ncurses requires it.
 */
#include <stdbool.h>

/**
 * Initialize the split-screen TUI
 *
 * Sets up ncurses, creates windows for header, game area, sidebar, and footer.
 * Checks ZORK_TUI_DISABLE environment variable - if set, TUI is disabled
 * and all functions become no-ops (falls back to plain text output).
 *
 * Call once at program startup before any text output.
 *
 * @return 0 on success, -1 on error (e.g., terminal too small, ncurses failure)
 */
int tui_init(void);

/**
 * Check if TUI is enabled
 *
 * Returns false if TUI was disabled via environment variable or failed to initialize.
 * When disabled, all TUI functions become no-ops.
 *
 * @return true if TUI is active, false otherwise
 */
bool tui_is_enabled(void);

/**
 * Display text in the main game area
 *
 * Appends text to the scrolling game window. Text will wrap and scroll automatically.
 * Handles newlines and special characters properly.
 *
 * Called from os_display_string() in doutput.c.
 *
 * @param text Text to display (can contain newlines, UTF-8, etc.)
 */
void tui_display_text(const char *text);

/**
 * Update the header bar
 *
 * Refreshes the header to show current game mode and LLM agent status.
 * Checks which LLM services are active and displays status indicators:
 * - 🤖 T (Translator)
 * - 🎨 A (Artist)
 * - 💬 DM (Dungeon Master)
 * - 🎮 P (Player Agent)
 *
 * Green checkmark (✓) = active, Red X (✗) = inactive
 *
 * Call this periodically or when LLM status changes.
 */
void tui_update_header(void);

/**
 * Update the sidebar (ASCII art, inventory, journey map)
 *
 * Refreshes all three sidebar sections:
 * 1. ASCII art (top) - Current location visualization
 * 2. Inventory (middle) - Items player is carrying
 * 3. Journey map (bottom) - Recent locations visited
 *
 * Call this when:
 * - Player moves to a new location (journey tracking detects this)
 * - Inventory changes (take/drop commands)
 * - ASCII art is generated by the Artist agent
 */
void tui_update_sidebar(void);

/**
 * Read user input from footer
 *
 * Displays a prompt in the footer and reads a line of input from the user.
 * Supports:
 * - Command history (up/down arrow keys)
 * - Line editing (backspace, left/right arrows)
 * - Tab completion (future enhancement)
 *
 * This is called from os_read_line() in dinput.c.
 *
 * @param prompt Prompt string to display (e.g., "> ")
 * @param buf Buffer to store input
 * @param bufsize Size of buffer
 * @return Number of characters read, or -1 on error/EOF
 */
int tui_read_input(const char *prompt, char *buf, int bufsize);

/**
 * Handle terminal resize
 *
 * Called when SIGWINCH is received (terminal window resized).
 * Recreates all windows with new dimensions and redraws content.
 *
 * ncurses handles most of this automatically, but we need to adjust
 * our window layout proportions (70/30 split).
 */
void tui_handle_resize(void);

/**
 * Shut down the TUI
 *
 * Cleans up ncurses resources and restores terminal to normal mode.
 * Call once at program exit.
 */
void tui_shutdown(void);

/**
 * Force a full refresh of all windows
 *
 * Useful for debugging or after external changes to the terminal.
 */
void tui_refresh_all(void);

#endif /* TT_ZORK_TUI_SPLIT_SCREEN_H */
